name: deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      target: ${{ inputs.target }}
    name: "deploy to $target"
    environment: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v2
      - name: echo test
        run: echo ${{ inputs.target }}