name: deploy

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

env:
  target: ${{ inputs.target }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: deploy to ${{ inputs.target }}
    environment: ${{ inputs.target }}
    steps:
      - uses: actions/checkout@v2
      - name: echo test
        run: echo ${{ inputs.target }} ${{ github.repository }}