name: release2
on:
  workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/deploy/deploy.yml
    with:
      target: ${{ matrix.target }}
