name: release2
on:
  push:
    tags:
      - v*

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: .github/workflows/deploy.yml@main
    with:
      target: ${{ matrix.target }}
